# Generated by Django 3.2.9 on 2021-12-08 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.PositiveIntegerField(null=True)),
                ('employeeId', models.PositiveIntegerField(null=True)),
                ('scheduleStart', models.DateTimeField()),
                ('scheduleFinish', models.DateTimeField()),
                ('scheduleInfo', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.PositiveIntegerField(null=True)),
                ('assignedEmployeeId', models.PositiveIntegerField(null=True)),
                ('taskTitle', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=500)),
                ('admitDate', models.DateField(auto_now=True)),
                ('deadLineDate', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompleteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.PositiveIntegerField(null=True)),
                ('taskTitle', models.CharField(max_length=40)),
                ('assignedEmployeeName', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('admitDate', models.DateField()),
                ('deadlineDate', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('comment', models.TextField(max_length=500, null=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(choices=[('Administrator', 'Administrator'), ('IT Support', 'IT Support')], default='Administrator', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
