# Generated by Django 3.2.9 on 2021-12-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runsheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='admitDate',
            new_name='assignDate',
        ),
        migrations.RenameField(
            model_name='taskcompletedetails',
            old_name='admitDate',
            new_name='assignDate',
        ),
    ]
