# Generated by Django 3.2.9 on 2021-12-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runsheet', '0002_auto_20211209_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadLineDate',
            new_name='deadlineDate',
        ),
    ]
