# Generated by Django 3.2.9 on 2021-12-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runsheet', '0003_rename_deadlinedate_task_deadlinedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskId',
        ),
    ]
